spring.application.name=doubt

server.servlet.context-path=/doubt
server.port=8000

spring.datasource.url=jdbc:postgresql://${DB_URL:db:5432}/${DB_DATABASE:doubt}
spring.datasource.username=${DB_USER:kainom}
spring.datasource.password=${DB_PASSWORD:1234}
spring.jpa.hibernate.ddl-auto=update
jwt.secret=your_jwt_secret
jwt.expiration=${JWT_EXP:86400000}

# Give more time for long-running APIs
spring.lifecycle.timeout-per-shutdown-phase=60s

# Reject new requests immediately during shutdown
server.shutdown=graceful
server.tomcat.threads.keep-alive-timeout=5s
